version: '2.3'

services:
  redis:
    image: redis:7.2-alpine
    container_name: local-redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    command: redis-server --save 20 1 --loglevel warning
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli ping | grep PONG']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis-data:
    driver: local
